---
- name: To check the ip
  hosts: ansible_client
  tasks:
    - name: Get network interfaces information
      shell: ps
      register: network_output

    - name: Display network output
      debug:
        var: network_output.stdout_lines


