---
- name: Check processes using Ansible
  hosts: ansible_client
  tasks:
    - name: Get list of running processes
      shell: ps aux
      register: process_output

    - name: Display process output
      debug:
        var: process_output.stdout_lines


